[package]
name = "x11rb-async"
version = "0.9.0"
description = "Async Rust bindings to X11"
authors = [
    "Uli Schlachter <psychon@znc.in>",
    "Eduardo Sánchez Muñoz <esm@eduardosm.net>",
]
repository = "https://github.com/psychon/x11rb"
readme = "README.md"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["xcb", "X11"]

[dependencies]
x11rb = { path = "..", version = "0.9" }
# TODO: Strip down features
tokio = { version = "1", features = ["full"] }
